import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer/footer'
import Header from './components/header/header'
import Sidebar from './components/sidebar/sidebar'
import "bootstrap-icons/font/bootstrap-icons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Popular-Safi',
  description: 'Generated by RahamsisCG.',
  // icons: '/faviconDepsac.ico',
  // openGraph: {
  //   title: 'DEPSAC ',
  //   description: 'Diseño de equipos y proyectos',
  //   url: 'https://depsac.com.pe',
  //   images: [
  //     {
  //       url: 'https://depsac.com.pe/depsac_miniatura.png',
  //       width: 1200,
  //       height: 630,
  //       alt: 'Imagen de vista previa',
  //     },
  //   ],
  //   type: 'website',
  // },
  // twitter: {
  //   card: 'summary_large_image',
  //   title: 'DEP sac',
  //   description: 'Diseño de equipos y proyectos',
  //   images: ['https://depsac.com.pe/depsac_miniatura.png'],
  // },
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {



  return (
    <html lang="es">
      {/* <head>
        Etiquetas meta adicionales para compartir correctamente */}
      {/* <meta property="og:title" content="DEPSAC" />
        <meta property="og:description" content="Diseño de equipos y proyectos" />
        <meta property="og:image" content="https://depsac.com.pe/depsac_miniatura.png" />
        <meta property="og:url" content="https://depsac.com.pe" />
        <meta property="og:type" content="website" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="DEP sac" />
        <meta name="twitter:description" content="Diseño de equipos y proyectos" />
        <meta name="twitter:image" content="https://depsac.com.pe/depsac_miniatura.png" />
        <link rel="icon" href="/faviconDepsac.ico" />
      </head> */}
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <Sidebar />
          <div className="flex flex-col flex-1 overflow-hidden">
            <Header />
            <main className="flex-1 overflow-y-auto p-4 md:p-6 bg-gray-50">
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
